[solver]
executable = '.\histra\SolverHistra.exe'
mode = "local"
process_name = "SolverHistra.exe"
close_without_ask = true

[runner]
workspace_root = './work'
keep_raw_on_success = true
keep_raw_on_failure = true
